name: bluesky_apod_bot
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  bluesky: ^0.8.0
  bluesky_text: ^0.3.0
  http: ^1.1.0
  image: ^4.0.15
  nasa: ^0.0.3

dependency_overrides:
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
