name: bluesky_apod_bot

environment:
  sdk: ^3.0.0

dependencies:
  aws_lambda_dart_runtime_ns: ^0.0.12
  bluesky: ^0.15.17
  bluesky_text: ^0.6.9
  http: ^1.2.1
  image: ^4.0.15
  nasa: ^0.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
