name: bluesky_apod_bot
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bluesky: ^0.7.9
  bluesky_text: ^0.2.7
  http: ^0.13.5
  image: ^4.0.15
  nasa: ^0.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
